---
apiVersion: v1
kind: Deployment
metadata:
  name: kafka-monitor
  labels:
    app: kafka-monitor
spec:
  replicas: {{.Values.replicas}}
  selector:
    matchLabels:
      app: kafka-monitor
  template:
    metadata:
      labels:
        app: kafka-monitor
    spec:
      containers:
        - name: kafka-monitor
          image: {{.Values.kafka_monitor_image}}
          imagePullPolicy: Always
          ports:
          - containerPort: {{.Values.kafka_monitor_gui_port}}
            name: gui
          - containerPort: {{.Values.kafka_monitor_metrics_port}}
            name: metrics
          volumeMounts:
            - name: config-volume
              mountPath: {{.Values.kafka_monitor_config_path}}
      volumes:
        - name: config-volume
          configMap:
            name: kafka-monitor-properties
            items:
            - key: kafka-monitor.properties 
