---
apiVersion: v1
kind: Service
metadata:
  name: kafka-monitor
  labels:
    app: kafka-monitor
    namespace: {{.Values.namespace}}
spec:
  type: LoadBalancer
  ports:
  - port: {{.Values.kafka_monitor_gui_port}}
    name: gui
  - port: {{.Values.kafka_monitor_metrics_port}}
    name: metrics
  selector:
    app: kafka-monitor
