---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: prometheus
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      name: prometheus
  template:
    metadata:
      labels:
        cagby.io/color: {{.Values.color}}
        name: prometheus
    spec:
      containers:
        - name: prometheus
          image: {{.Values.prometheus_image}}
          imagePullPolicy: Always
          args:
            - '-config.file=/etc/prometheus/prometheus.yml'
          ports:
            - containerPort: {{.Values.prometheus_port}}
              hostPort: {{.Values.prometheus_port}}
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/prometheus/
              name: prometheus-config-volume
            - mountPath: /prometheus
              name: prometheus-data-volume
            - mountPath: /backup
              name: prometheus-backup-volume
        - name: pushgateway
          image: {{.Values.pushgateway_image}}
          ports:
            - containerPort: {{.Values.pushgateway_port}}
              hostPort: {{.Values.pushgateway_port}}
              protocol: TCP
        - name: pause
          image: gcr.io/google-containers/pause:2.0
          volumeMounts:
            - mountPath: /prometheus
              name: prometheus-data-volume
            - mountPath: /backup
              name: prometheus-backup-volume
      dnsPolicy: ClusterFirst
      # http://kubernetes.io/docs/user-guide/pod-states/#container-probes
      restartPolicy: Always
      volumes:
        - name: prometheus-config-volume
          configMap:
            name: prometheus
        - name: prometheus-data-volume
          emptyDir: {}
        - name: prometheus-backup-volume
          emptyDir: {}
